# Read about `build.yaml` at https://pub.dartlang.org/packages/build_config

builders:
  versionName:
    import: 'tool/version_generator.dart'
    builder_factories: ["versionNameBuilder"]
    build_extensions: {".dart": [".g.dart"]}
    auto_apply: root_package
    build_to: source
    defaults:
      generate_for:
        - 'lib/cli_app.dart'