name: git_revision
version: 0.5.1
description: Revision calculator for git projects
#homepage: https://pascalwelsch.com
author: Pascal Welsch <pascal.welsch@gmail.com>

environment:
  sdk: '>=2.0.0-dev.61.0 <3.0.0'

dependencies:
  args: '^1.2.0'

dev_dependencies:
  test: '^1.2.0'
  mockito: '^3.0.0-beta+1'
  build: '^0.12.6'
  source_gen: '^0.8.1+1'
  build_config: '^0.3.0'
  build_runner: '^0.9.0'
  dart_style: '^1.1.2'

executables:
  # a valid dart filename doesn't contain a dash -> remapping
  git-revision: git_revision