name: git_revision
version: 0.5.0
description: Revision calculator for git projects
#homepage: https://pascalwelsch.com
author: Pascal Welsch <pascal.welsch@gmail.com>

environment:
  sdk: '>=2.0.0-dev.62.0'

dependencies:
  args: '^1.2.0'

dev_dependencies:
  test: '^1.2.0'
  mockito: '^3.0.0-beta+1'

executables:
  # a valid dart filename doesn't contain a dash -> remapping
  git-revision: git_revision