name: git_revision
version: 0.4.0
description: Revision calculator for git projects
#homepage: https://pascalwelsch.com
author: Pascal Welsch <pascal.welsch@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  args: '1.2.0'

dev_dependencies:
  test: ^0.12.0
  mockito: ^2.2.1

executables:
  # a valid dart filename doesn't contain a dash -> remapping
  git-revision: git_revision